name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Static syntax check
        run: |
          python -m compileall -q .

      - name: Run tests (if pytest available)
        run: |
          if python -c "import importlib, sys; sys.exit(0 if importlib.util.find_spec('pytest') else 1)"; then \
            python -m pytest -q; \
          else \
            echo "pytest not installed; skipping tests"; \
          fi

